### ISSUE TITLE
Documentation mistakes

### ISSUE THREAD

**Issue by ghost** [samsmithnz/lead-time-for-changes#21]
The documentation references `deployment-frequency` instead of `lead-time-for-changes`.. in 

```
- name: Test another repo
  uses: samsmithnz/deployment-frequency@main
  with:
    workflows: 'CI/CD'
    owner-repo: 'samsmithnz/DevOpsMetrics'
    default-branch: 'main'
    number-of-days: 30
```
